In [3]:
import numpy as np

In [4]:
a = np.random.randn(5)
a

array([ 1.1460958 , -0.40624344, -1.96571035,  1.3870619 ,  1.05422934])

In [5]:
a.shape

(5,)

In [6]:
a.T

array([ 1.1460958 , -0.40624344, -1.96571035,  1.3870619 ,  1.05422934])

In [7]:
np.dot(a, a.T)

8.377926701172484

In [32]:
# we do the followings instead
b = np.random.randn(4,1)
b

array([[ 0.79231574],
       [ 0.58694181],
       [-0.70815567],
       [ 0.74613867]])

In [33]:
b.T

array([[ 0.79231574,  0.58694181, -0.70815567,  0.74613867]])

In [15]:
print(np.dot(b, b.T))

[[ 0.3386643  -0.08403748 -0.05611779 -0.12501265]
 [-0.08403748  0.02085339  0.01392529  0.03102113]
 [-0.05611779  0.01392529  0.0092989   0.02071501]
 [-0.12501265  0.03102113  0.02071501  0.04614647]]
