In [1]:
import numpy as np

In [4]:
A = np.array([[56, 0, 67],
              [1.2, 104, 65],
              [1.8, 135, 66]])
A

array([[ 56. ,   0. ,  67. ],
       [  1.2, 104. ,  65. ],
       [  1.8, 135. ,  66. ]])

In [5]:
total = np.sum(A, axis=0) # axis=0，跨行计算，就是按列计算
total

array([ 59., 239., 198.])

In [8]:
percentage = 100 * A / total
percentage

array([[94.91525424,  0.        , 33.83838384],
       [ 2.03389831, 43.51464435, 32.82828283],
       [ 3.05084746, 56.48535565, 33.33333333]])